### ISSUE TITLE
I'm in

### ISSUE THREAD

**Issue by lnishan** [shaform/csdream#5]
Creating this issue to let you know that:
I think I would work on updating this repo once I'm done with school work this semester.
(or maybe adding new stuff in, but mostly updating I would think).

Thank you for creating the site :)
Cheers

**Comment by lnishan** [comment]
Perhaps for a start, the [Awesome Lists](https://github.com/sindresorhus/awesome) would be a great addition to the resource category.

I also have one for [competitive programming](https://github.com/lnishan/awesome-competitive-programming) (I guess I'll try incorporating it into `problem-solving.md` ?)

**Comment by shaform** [comment]
Thank you for your contributions!
